repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-symlinks
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-ast
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-private-key
  - id: debug-statements
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.1
  hooks:
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi ]
