name: lint

on:
  pull_request:
  push:
    branches-ignore: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: >
            --all-files
